global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alert.rules.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'snmp'
    metrics_path: /snmp
    params:
      module: [if_mib, mikrotik]
    static_configs:
      - targets:
          - 103.105.129.134
          - 103.177.215.231
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 103.177.215.231:9116
 
