global:
  scrape_interval: 60s
  evaluation_interval: 60s

rule_files:
  - /etc/prometheus/alert.rules.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'snmp-mikrotik'
    metrics_path: /snmp
    params:
      module: [mikrotik]
    static_configs:
      - targets:
          - 103.105.129.134  # IP Mikrotik
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 213.163.198.21:9116  # SNMP Exporter address

